# Generated by Django 4.0.6 on 2022-11-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('tourplan', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
