# Generated by Django 4.0.6 on 2022-11-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_place_tourplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.CharField(default='Uttarkashi', max_length=100),
            preserve_default=False,
        ),
    ]
